version:  "2"

services:
    application:
        image: unicef/indiaapp
        ports:
            - "8005:8000"
        depends_on:
            - database

    database:
        image: unicef/indiadb